- name: Intelora Repeat neuron install
  hosts: localhost
  gather_facts: no
  connection: local
  become: false

  tasks:
    - name: "Install pip dependencies"
      debug:
          msg: "no pip packages required"
